language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install -U pip setuptools
install:
- pip install pipenv
- pipenv install --dev --skip-lock
before_script:
- nosetests -v
script:
- invoke test.lint
- invoke test.security
- invoke unit.pytest
- invoke integration.version
deploy:
  provider: pypi
  user: __token__
  password:
    secure: xpiZF+qCmesS2Qib2blwc0arsEc3PWl8nAB2AIeNmT6iHkIDezkuh/i9pe4VNq0jj/68YFMhQDKbILyQiFwi2HcS/5Jy60l4+07XMC6+LVHS4i1s5ZWFC4HCHPFDGhY6qp7TPjKsUNpBK41O0ojkAsAKqVb9VB/1ckEBNRPJA8FeAca1dW5NGF4CuPFZM0yXjI0uWiNMmZE2ya6PYhBZPSIHw2L8Ctvo/F56/OGIPyIhPLBCyPy3lGkvuWbN00pqROfkni9Nb8V7XQz+xQWwoBhYBJS6ESbItgOq8JlDjSVP0FjUI6Y+bPbPSFDjAGWQ/m3XQXAz8QgsBT2KJkneYxjWamO/Mf66UmYU58g71UvVtIGByWYqS6JRa12Hg/t4B79sZMQVyOQQ4MRaTVOD5t+Nzb29OeUEJUP2puC1Imcrl+oRzdGSFRsou+tC2FgjQl7AQgtqnOSPehjNHlGZlWZTiAML1j70B8SsAcs+8pUDy7HdUg/3XsfvspiKE+cPoZuUQQDmpl5MLF7+JTif5rCZWopjw2FunMndi1SdeUmvytoS7MJ1KOpz5E8u99MCN7+krhvpqjkyGi8wmRYqpHA/MTZrrA6AeIYNfVpaG5M8wMtyDHB11fxI/GnHh6g5LoenrrSizrjWIZSdCGAtoY+/vI4sug6fa2IeLnfPB8w=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    branch: master
    skip_existing: true
    python: 3.6
