language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install -U pip setuptools
install:
- pip install pipenv
- pipenv install --dev --skip-lock
before_script:
- nosetests -v
script:
- invoke test.lint
- invoke test.unit
deploy:
  provider: pypi
  user: __token__
  password:
    secure: K0MT6q6ysq+i/7Uto/+uWWS41IHCrsYo6AaHiOTGXCKAMlhNU2K5D5HQG6jDC5z6JvYPYYn7W+mtf4mTI5g3Qzlgx14ZC95ckvojmSU8hb3YDmStqKQ14u2k/np05SylcfXET7FMuYMzOGRWihgz9EVtmW4cNZcga4ejA8uod5DGVk0KmVcURMBMZ5ja3TErlHsywDHnZIyjbHIDNoXVUIeuK1zaTLGr6f5t4J2Q+vAcuGGH7jWWokpcwLQodh+D63PkIrC7Y+LXnDmtBmZmGNykkXG2HC2FH0Hxw3OZV4trz070c5t1QpsgJeos2rc8DzVgJT4/N38HW1q41OuC1geZms/DY9RKT6W+FSWOAedc/Y93Bdr9BirRZq7remyzuJpxQk8R6uA99OPPjl6QY9GxpGfqhva1JeqwQzD1+cdN8Tj2JQICJJEFS8/aX0vULAMqvnAMxczuwxUyII0gts0MStJ753v6WshailWoyvq+nVoSN1042vBR9isYdsWIW1nd/fZoiNgXhqIOeP1Rf6C6cqdwkPhkCNeZbAVvctjSYFxsmn8uBfugB+ED2knD1CuzbP8kKqg21HQ4pUrsCb5SoADsck2AHMBz/kR/WQaHqS21SzMrCB3UQos0+qqQ2b4ZEEmttATSpElVBHB3kRM17Faobt0H35J+MjsoP4k=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    branch: master
    python: 3.7
