language: python
python:
  - "3.7"
before_install:
  - pip install -U pip setuptools
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
# verify the version is legit
before_script:
  - nosetests -v
# For some reason, this is exiting with error 255.
#  - invoke test.security
script:
  - invoke test.lint
  - invoke test.unit

deploy:
  provider: pypi
  user: kinnairdm
  password:
    secure: "IThUcfla3ntLhtkZJuAUgILo4m1v3de23Is2F9IJ+dV55XRX0zHeUtpmjtXJkaAf1ul+rNqYFTDQSKoOcFpBEt7q6KKYpQ6h12VwUhIC2bXgeWBNWU4d0/xB07ZSG15OcIuzsWZC5U8K/aOi9Btx8sQ4mXEOVYgsodSZe96URy86gP55vviKzFnr3Xvtn9pOk9eUL6jEINw+Tz8MUoS/kUqpU2Bue9OmHpWnYCdxaAr7dqHyJ99YOO04agIlrPnY+olvtKbvHSvUl8XkXGcaTvhm9EGVlVXX9rXwzkkVKLN2LCxkViNXVjfbJbJZXEpmo3H/Av3mjTSxtWAqHN1kR6ldugQGjIHjTWsJ2+KGloRLjAlIQ77ZcKf+r9gyoZuGsTPMCPuZzNkMgIaAYzP1rjeiDSozXjqVaRX59Mg6OOQ6I2K5CVQV7e9/BtaN8yh9xirRvNCDIuBd6pCf69N1pFe3lWC5U0a5INCm4CIUX12RBnHIMB+UQzUSUm5Ux95YtS2BCtM8gytkicX8Y+XXhR7mv/Yr4hvgLoURKEbC0VyAWdZ1y0cLhgJ/ROAWQROkZiR4zj0YqavuLjirjoi7gtR7Bgh3Rmvd+s+SQhid13PO1U/lOeBMfmx94gNwMmR8QroMpIfDrDyz9klx3xG/kgFhokViowN6CK/Nij2+wjs="
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true # only deploy on tagged commits
    branch: master # must come from master branch
    python: 3.7