# .github/workflows/publish.yml

name: Publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --dev --skip-lock

      - run: pipenv run invoke test.lint
#      - run: pipenv run invoke test.security
      - run: pipenv run invoke unit.pytest
      - run: pipenv run invoke integration.version
      - run: pipenv run invoke build.uninstall-package

  publish-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull origin master
          pipenv run python setup.py sdist bdist_wheel
      - name: Upload python package to release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'dist/*'

  update-brew:
    needs: publish-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: publish brew
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv run pip install homebrew-pypi-poet
          pipenv run pip install washington_football -U
          git fetch origin
          git checkout --track origin/master
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          git pull origin $latest_tag
          pipenv run poet -f washington_football > HomebrewFormula/washington_football.rb
          git add .
          git commit -m "update brew formula" washington_football/bin/washington_football HomebrewFormula/washington_football.rb || echo "No brew changes to commit"
          git push -u origin master

  bump-version:
    runs-on: ubuntu-latest
    needs: update-brew
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: |
          version_file="washington_football/bin/version.py"
          # https://github.com/bridgecrewio/checkov/blob/master/.github/workflows/build.yml#L87-L132
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull origin master
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          echo "new tag: $new_tag"
          printf "# pylint: disable=missing-module-docstring\n__version__ = '$new_tag'""" > $version_file
          git commit -m "Bump to ${new_tag}"  $version_file || echo "No changes to commit"
          git push origin
